### ISSUE TITLE
Mac, Windows で動作しない

### ISSUE THREAD

**Issue by rnanba** [rnanba/HatenaBlogWriter#1]
http://ima.hatenablog.jp/entry/2017/06/06/134055

Windows で以下のエラーでエントリファイルをアップロードできない。
```
C:\hbw>hbw.rb
新規エントリファイルが 1 件あります。
C:/hbw/HatenaBlogWriter.rb:118:in `match': invalid byte sequence in Windows-31J (ArgumentError)
        from C:/hbw/HatenaBlogWriter.rb:118:in `block in parse_file'
        from C:/hbw/HatenaBlogWriter.rb:115:in `each_line'
        from C:/hbw/HatenaBlogWriter.rb:115:in `parse_file'
        from C:/hbw/HatenaBlogWriter.rb:106:in `initialize'
        from C:/hbw/HatenaBlogWriter.rb:228:in `new'
        from C:/hbw/HatenaBlogWriter.rb:228:in `post'
        from C:/hbw/hbw.rb:109:in `block in<main>'
        from C:/hbw/hbw.rb:105:in `each'
        from C:/hbw/hbw.rb:105:in `<main>'
```

Mac では以下のエラーで同様。
```
mymac:hbw$ ruby hbw.rb
新規エントリファイルが 1 件あります。
/Library/Ruby/Gems/2.0.0/gems/atomutil-0.1.4/lib/atomutil.rb:1523:in `block in get_contents_except_resources': Failed to get contents. 404 (Atompub::RequestError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:852:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:582:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/atomutil-0.1.4/lib/atomutil.rb:1517:in `get_contents_except_resources'
	from /Library/Ruby/Gems/2.0.0/gems/atomutil-0.1.4/lib/atomutil.rb:1350:in `get_service'
	from /Users/hoge/hbw/HatenaBlogWriter.rb:216:in `ensure_get_service'
	from /Users/hoge/hbw/HatenaBlogWriter.rb:236:in `post'
	from hbw.rb:109:in `block in <main>'
	from hbw.rb:105:in `each'
	from hbw.rb:105:in `<main>'
```

**Comment by rnanba** [comment]
Mac (OS X 10.11.6, ruby 2.0.0p648)では投稿、更新ともに正常動作。
Macはロケールが ja_JP.UTF-8 なので開発環境(Ubuntu 16.04)と同じで文字エンコーディング周りの問題は出ないはず。エラーを見るとサーバーエラー(404)なので Mac の方は別の問題?

**Comment by rnanba** [comment]
Windows (Windows 10, RubyInstaller2.4)で再現を確認。

**Comment by rnanba** [comment]
a98353ee650719faa1bba9a031c4683138bddfa7 で修正した。
