### ISSUE TITLE
いったん公開したエントリを「draft: yes」にして再投稿するとエラーが出る?

### ISSUE THREAD

**Issue by imamurayusuke** [rnanba/HatenaBlogWriter#10]
```
修正されたエントリファイルが 1 件あります。
Traceback (most recent call last):
        8: from C:/hbw.rb:142:in `<main>'
        7: from C:/hbw.rb:142:in `each'
        6: from C:/hbw.rb:146:in `block in <main>'
        5: from C:/HatenaBlogWriter.rb:353:in `update'
        4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/atomutil-0.1.5/lib/atomutil.rb:1474:in `update_entry'
        3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/atomutil-0.1.5/lib/atomutil.rb:1614:in `update_resource'
        2: from C:/Ruby25-x64/lib/ruby/2.5.0/net/http.rb:609:in `start'
        1: from C:/Ruby25-x64/lib/ruby/2.5.0/net/http.rb:910:in `start'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/atomutil-0.1.5/lib/atomutil.rb:1627:in `block in update_resource': Failed to update resource. 400 (Atompub::RequestError)
```

エラーの発生条件を詰めきれていませんが、おそらくということでご報告です。

**Comment by rnanba** [comment]
README.md の注意事項にあるように、一度公開したエントリを下書きに戻すことは今のところできません。はてなのAPI側でエラーを出すのでAPIの制限事項かと思ったのですが、ドキュメントには特に記載はないですし、Webからだと下書きに戻せるので、バグなのかも… 今度はてなに問い合わせておきます。

**Comment by imamurayusuke** [comment]
注意事項を見落としていました。スイマセン。
