### ISSUE TITLE
HatenaBlogWriter.rbの140行目でundefined method

### ISSUE THREAD

**Issue by imamurayusuke** [rnanba/HatenaBlogWriter#5]
https://github.com/rnanba/HatenaBlogWriter/blob/38c4f0bb4467c13007da2fb5ea368b0d80715a62/HatenaBlogWriter.rb#L140

でエラーが出ました。（Windows）

```
C:/HatenaBlogWriter.rb:140:in `block in parse_file': undefined method `match?' for /^yes$/:Regexp (NoMethodError)
Did you mean?  match
        from C:/HatenaBlogWriter.rb:120:in `each_line'
        from C:/HatenaBlogWriter.rb:120:in `parse_file'
        from C:/HatenaBlogWriter.rb:107:in `initialize'
        from C:/hbw.rb:37:in `new'
        from C:/hbw.rb:37:in `block in modified_files_to_update'
        from C:/hbw.rb:32:in `foreach'
        from C:/hbw.rb:32:in `modified_files_to_update'
        from C:/hbw.rb:120:in `<main>'
```

「match?」を「match」に変更したところ正常に動作しました。

ご確認下さい。

**Comment by rnanba** [comment]
ruby のバージョンは 2.3 またはそれ以前でしょうか？
`match?` は Ruby 2.4 からのようですね。2.4 以降に限定する必然性もなさそうなので対応します。

**Comment by imamurayusuke** [comment]
お察しの通り以下でした。

ruby 2.3.0p0 (2015-12-25 revision 53290) [x64-mingw32]

なるほど、rubyのバージョンで動作が変わるんですね。

**Comment by rnanba** [comment]
v0.8.2 で修正しました。
