### ISSUE TITLE
v0.8.3のhbwdl.rbがエラーになる

### ISSUE THREAD

**Issue by imamurayusuke** [rnanba/HatenaBlogWriter#8]
hbwでの更新はできているのですが、```hbwdl.rb 0```で下のエラーが出ます。（数字を変えても同様）

```
C:/HatenaBlogWriter.rb:35:in `glob': no implicit conversion of Hash into Integer (TypeError)
        from C:/HatenaBlogWriter.rb:35:in `listData'
        from C:/hbwdl.rb:8:in `load_db'
        from C:/hbwdl.rb:59:in `<main>'
```

rubyのバージョンは2.4.5p335 (2018-10-18 revision 65137) [x64-mingw32]です。

わかることがありましたら教えて下さい。

**Comment by rnanba** [comment]
```
      return Dir.glob("*.dat", base: DATA_DIR).map() { |data_filename|
```
ここの `base:` 引数が Ruby 2.5 以降の機能のようです。2.4 以前でも動くように書き換えますのでしばらくお待ちください。

**Comment by rnanba** [comment]
修正してみました。ご確認ください。

**Comment by imamurayusuke** [comment]
できました！ありがとうございました。
